// Generated by CoffeeScript 2.3.2
var Application, ApplicationMounted;

Application = {
  view: function() {
    return [m("h1", "AAAa")];
  }
};

m.mount(document.body, Application);

ApplicationMounted = true;
